language: java
jdk: oraclejdk8
jobs:
  include:
    - stage: test
      script: mvn clean install -e
    - stage: perf test
      script: cd /performance-testing && mvn clean install -e -Pperformance-benchmark